version: '3.8'

# This file provides development-specific overrides
# It will be automatically loaded by docker-compose

services:
  php:
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    
  vite:
    environment:
      - NODE_ENV=development
      - VITE_DEV_SERVER_HOST=0.0.0.0
      - VITE_DEV_SERVER_PORT=5173
